[package]
name = "mdbxtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmdbx = "0.1.8"
hex = "0.4"
rand = "0.8"
tempfile = "3.3.0"
